/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.SistemaGestaoDao;
import java.sql.*;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author welli
 */
public class AlterarProduto extends javax.swing.JFrame {

    /**
     * Creates new form AlterarProduto
     */
    public AlterarProduto() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        txtCodProd = new javax.swing.JTextField();
        btnAlterProd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAlterProd1 = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtQtdProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CÓDIGO:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 20, 90, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NOME DO PRODUTO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 70, 210, 40);

        txtNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeProd);
        txtNomeProd.setBounds(260, 70, 390, 40);

        txtCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodProd);
        txtCodProd.setBounds(260, 20, 100, 40);

        btnAlterProd.setBackground(new java.awt.Color(255, 0, 0));
        btnAlterProd.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnAlterProd.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterProd.setText("CANCELAR");
        btnAlterProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterProd);
        btnAlterProd.setBounds(500, 190, 150, 40);

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LIMPAR CAMPOS");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 120, 190, 40);

        btnAlterProd1.setBackground(new java.awt.Color(0, 153, 0));
        btnAlterProd1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnAlterProd1.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterProd1.setText("CONFIRMAR ALTERÇÃO");
        btnAlterProd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterProd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterProd1);
        btnAlterProd1.setBounds(180, 190, 280, 40);

        btnBuscarProd.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscarProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBuscarProd.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarProd.setText("BUSCAR");
        btnBuscarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProd);
        btnBuscarProd.setBounds(670, 70, 130, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("QUANTIDADE:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 120, 140, 40);

        txtQtdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdProdActionPerformed(evt);
            }
        });
        jPanel1.add(txtQtdProd);
        txtQtdProd.setBounds(260, 120, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 70, 820, 250);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("ALTERAR PRODUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 10, 220, 40);

        tblProdutos.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "QUANTIDADE"
            }
        ));
        tblProdutos.setRowHeight(30);
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 360, 930, 340);

        setSize(new java.awt.Dimension(1010, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdActionPerformed

    private void txtCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdActionPerformed

    }//GEN-LAST:event_txtCodProdActionPerformed

    private void btnAlterProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterProdActionPerformed
        dispose();
    }//GEN-LAST:event_btnAlterProdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome, qtd;

        nome = txtNomeProd.getText();
        qtd = txtCodProd.getText();

        txtNomeProd.setText("");
        txtCodProd.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAlterProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterProd1ActionPerformed
        String nomeProd;
        int quantidade, codigoProd;
        nomeProd = txtNomeProd.getText();
        if (nomeProd.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma Produto Selecionado! ");
        } else {

            

            try {
                quantidade = Integer.parseInt(txtQtdProd.getText());
                codigoProd = Integer.parseInt(txtCodProd.getText());

                new SistemaGestaoDao().alterarProduto(nomeProd, quantidade, codigoProd);

                txtCodProd.setText("");
                txtNomeProd.setText("");
                txtQtdProd.setText("");
                
               
                

                JOptionPane.showMessageDialog(rootPane, "Sucesso", "Dados alterados com sucesso!", 1);

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Quantidade Invalida!");

            }
        }
    }//GEN-LAST:event_btnAlterProd1ActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        String nomeProd;
        nomeProd = txtNomeProd.getText();

        try {
            ResultSet produtos = new SistemaGestaoDao().buscarProdutos(nomeProd);

            DefaultTableModel tblModelo = (DefaultTableModel) tblProdutos.getModel();
            tblModelo.setRowCount(0);

            while (produtos.next()) {
                String linha[] = {
                    produtos.getString("cod_prod"),
                    produtos.getString("nomeProd"),
                    produtos.getString("qtd"),};
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        if (tblProdutos.getSelectedRow() >= 0) {
            txtCodProd.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 0).toString());
            txtNomeProd.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 1).toString());
            txtQtdProd.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 2).toString());
            txtCodProd.setEnabled(false);
        }
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void txtQtdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterProd;
    private javax.swing.JButton btnAlterProd1;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtQtdProd;
    // End of variables declaration//GEN-END:variables

    private void listarProdutos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
