/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.SistemaGestaoDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author welli
 */
public class CadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        initComponents();
        listarProdutos();
    }
    
    private void listarProdutos(){
         try {
             ResultSet produtos = new SistemaGestaoDao().listarProdutos();
            
             
              DefaultTableModel tblModelo = (DefaultTableModel) tblProdutos.getModel();
              tblModelo.setRowCount(0);
              while(produtos.next()){
                  String linha[] = {
                      produtos.getString("nomeProd"),
                      produtos.getString("qtd")
                     
                  };
                  tblModelo.addRow(linha);
                  
              }
              
        } catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        txtQtdProd = new javax.swing.JTextField();
        btnCadastrarProd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAlterProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PRODUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 0, 120, 50);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("QUANTIDADE:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 80, 140, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NOME DO PRODUTO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 30, 210, 40);

        txtNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeProd);
        txtNomeProd.setBounds(250, 30, 390, 40);

        txtQtdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdProdActionPerformed(evt);
            }
        });
        jPanel1.add(txtQtdProd);
        txtQtdProd.setBounds(250, 80, 150, 40);

        btnCadastrarProd.setBackground(new java.awt.Color(0, 153, 0));
        btnCadastrarProd.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnCadastrarProd.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrarProd.setText("CADASTRAR");
        btnCadastrarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarProd);
        btnCadastrarProd.setBounds(180, 150, 170, 40);

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LIMPAR CAMPOS");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 80, 190, 40);

        btnAlterProd.setBackground(new java.awt.Color(255, 0, 0));
        btnAlterProd.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnAlterProd.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterProd.setText("CANCELAR");
        btnAlterProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterProd);
        btnAlterProd.setBounds(380, 150, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 50, 680, 210);

        tblProdutos.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NOME", "QUANTIDADE"
            }
        ));
        tblProdutos.setRowHeight(30);
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 270, 930, 290);

        setSize(new java.awt.Dimension(996, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdActionPerformed

    private void txtQtdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdProdActionPerformed
        
    }//GEN-LAST:event_txtQtdProdActionPerformed

    private void btnCadastrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdActionPerformed
        String nome;
       nome = txtNomeProd.getText();
      
        if (nome.isEmpty()) {
              JOptionPane.showMessageDialog(null, "[ERRO] Campos Vazios!");
     } else 
            try {
          int  quantidade = Integer.parseInt(txtQtdProd.getText());
            
           
         
          
           
           new SistemaGestaoDao().cadastrarProduto(nome, quantidade);
           JOptionPane.showMessageDialog(null, "Produto Cadastrado com Sucesso");
           
           txtNomeProd.setText("");
           txtQtdProd.setText("");
           listarProdutos();
           
           
           
           
       }catch (ClassNotFoundException | SQLException ex){
             if(ex.getMessage().contains("Duplicate entry")){
                 JOptionPane.showMessageDialog(null, "Produto já cadastrado");
             } else {
                  JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
             }   
             
            
        } catch (NumberFormatException ex){
           JOptionPane.showMessageDialog(null, "[ERRO] Quantidade Vazia! Insira '' 0 '' se não houver unidades do Produto!");
           
                   
                }
       
    }//GEN-LAST:event_btnCadastrarProdActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        if(tblProdutos.getSelectedRow() >= 0){
            txtNomeProd.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 0).toString());
             txtQtdProd.setText(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome, qtd;
        
        nome = txtNomeProd.getText();
        qtd = txtQtdProd.getText();
        
        txtNomeProd.setText("");
        txtQtdProd.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAlterProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterProdActionPerformed
        dispose();
    }//GEN-LAST:event_btnAlterProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterProd;
    private javax.swing.JButton btnCadastrarProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtQtdProd;
    // End of variables declaration//GEN-END:variables
}
