/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.SistemaGestaoDao;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author welli
 */
public class CadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarUsuario() {
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void verificarEnable() {
        if (painelUsuarioLogin.isEnabled() || painelCadastroUsu.isEnabled()) {
            fecharLogin();
            fecharCadastroUsu();
           
            
        }

    }
     
      private void mostrarLogin() {
        verificarEnable();
        painelUsuarioLogin.setEnabled(true);
        painelUsuarioLogin.setVisible(true);
    }

    private void fecharLogin() {
        painelUsuarioLogin.setEnabled(false);
       painelUsuarioLogin.setVisible(false);
    }
    
    private void mostrarCadastroUsu() {
        verificarEnable();
         painelCadastroUsu.setEnabled(true);
         painelCadastroUsu.setVisible(true);
    }

    private void fecharCadastroUsu() {
         painelCadastroUsu.setEnabled(false);
        painelCadastroUsu.setVisible(false);
    }
    
     
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelUsuarioLogin = new java.awt.Panel();
        pswSenha = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        ckMostrarSenha = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        painelCadastroUsu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        btnCadastrarUsu = new javax.swing.JButton();
        ckMostrarSenhaUsu = new javax.swing.JCheckBox();
        pswUsu = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        painelUsuarioLogin.setBackground(new java.awt.Color(255, 255, 255));
        painelUsuarioLogin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        painelUsuarioLogin.setEnabled(true);
        painelUsuarioLogin.setVisible(true);
        painelUsuarioLogin.setLayout(null);

        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });
        pswSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswSenhaKeyPressed(evt);
            }
        });
        painelUsuarioLogin.add(pswSenha);
        pswSenha.setBounds(40, 200, 230, 30);

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        painelUsuarioLogin.add(txtUsuario);
        txtUsuario.setBounds(40, 110, 230, 30);

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuário");
        painelUsuarioLogin.add(lblUsuario);
        lblUsuario.setBounds(40, 60, 90, 40);

        btnEntrar.setBackground(new java.awt.Color(0, 204, 0));
        btnEntrar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setMnemonic('E');
        btnEntrar.setText("ENTRAR");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntrarKeyPressed(evt);
            }
        });
        painelUsuarioLogin.add(btnEntrar);
        btnEntrar.setBounds(100, 290, 120, 41);

        lblSenha.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha");
        painelUsuarioLogin.add(lblSenha);
        lblSenha.setBounds(40, 150, 71, 50);

        ckMostrarSenha.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        ckMostrarSenha.setForeground(new java.awt.Color(0, 0, 0));
        ckMostrarSenha.setText("Mostrar a senha");
        ckMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMostrarSenhaActionPerformed(evt);
            }
        });
        painelUsuarioLogin.add(ckMostrarSenha);
        ckMostrarSenha.setBounds(40, 240, 170, 28);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOGUE COMO ADMINISTRADOR");
        painelUsuarioLogin.add(jLabel1);
        jLabel1.setBounds(30, 30, 290, 22);

        getContentPane().add(painelUsuarioLogin);
        painelUsuarioLogin.setBounds(80, 10, 330, 390);

        painelCadastroUsu.setBackground(new java.awt.Color(204, 204, 204));
        painelCadastroUsu.setVisible(false);
        painelCadastroUsu.setEnabled(false);

        painelCadastroUsu.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CADASTRAR USUARIO");
        painelCadastroUsu.add(jLabel2);
        jLabel2.setBounds(150, 10, 200, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SENHA:");
        painelCadastroUsu.add(jLabel3);
        jLabel3.setBounds(80, 130, 70, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("USUARIO:");
        painelCadastroUsu.add(jLabel4);
        jLabel4.setBounds(60, 70, 100, 40);
        painelCadastroUsu.add(txtUsu);
        txtUsu.setBounds(160, 70, 220, 40);

        btnCadastrarUsu.setBackground(new java.awt.Color(51, 204, 0));
        btnCadastrarUsu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCadastrarUsu.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrarUsu.setText("CADASTRAR");
        btnCadastrarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuActionPerformed(evt);
            }
        });
        painelCadastroUsu.add(btnCadastrarUsu);
        btnCadastrarUsu.setBounds(180, 220, 170, 50);

        ckMostrarSenhaUsu.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        ckMostrarSenhaUsu.setForeground(new java.awt.Color(0, 0, 0));
        ckMostrarSenhaUsu.setText("Mostrar a senha");
        ckMostrarSenhaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMostrarSenhaUsuActionPerformed(evt);
            }
        });
        painelCadastroUsu.add(ckMostrarSenhaUsu);
        ckMostrarSenhaUsu.setBounds(160, 170, 170, 28);
        painelCadastroUsu.add(pswUsu);
        pswUsu.setBounds(160, 130, 220, 40);

        getContentPane().add(painelCadastroUsu);
        painelCadastroUsu.setBounds(30, 50, 420, 270);

        setSize(new java.awt.Dimension(486, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenhaActionPerformed

    private void pswSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSenhaKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnEntrar.requestFocus();
        }
    }//GEN-LAST:event_pswSenhaKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed

        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            pswSenha.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String usuario, senha;
        usuario = txtUsuario.getText();
        senha = pswSenha.getText();

        if(usuario.isEmpty() || senha.isEmpty()){
            JOptionPane.showMessageDialog(null, "[ERRO] Campos Vazios!");
        }else

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario = ? AND senha = ?");
            st.setString(1, usuario);
            st.setString(2, senha);
            ResultSet usu = st.executeQuery();
            if(usu.next()){
                mostrarCadastroUsu();
              
                
                
               
            }else {
                JOptionPane.showMessageDialog(null, "[ERRO] Usúario ou Senha Inválidos");
            }

        } catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnEntrar.doClick(PROPERTIES);
        }
    }//GEN-LAST:event_btnEntrarKeyPressed

    private void ckMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMostrarSenhaActionPerformed

        if(ckMostrarSenha.isSelected()){
            pswSenha.setEchoChar((char)0);
        }else {
            pswSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_ckMostrarSenhaActionPerformed

    private void ckMostrarSenhaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMostrarSenhaUsuActionPerformed

        if(ckMostrarSenhaUsu.isSelected()){
            pswUsu.setEchoChar((char)0);
        }else {
            pswUsu.setEchoChar('*');
        }
    }//GEN-LAST:event_ckMostrarSenhaUsuActionPerformed

    private void btnCadastrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuActionPerformed
        String usu, senha;
        usu = txtUsu.getText();
        senha = pswUsu.getText();
        
        try {
            new SistemaGestaoDao().cadastrarUsuario(usu, senha);
            
             JOptionPane.showMessageDialog(null, "Usuario  Cadastrado com Sucesso");
             
             txtUsu.setText("");
             pswUsu.setText("");
             
            
        }catch (ClassNotFoundException | SQLException ex){
             if(ex.getMessage().contains("Duplicate entry")){
                 JOptionPane.showMessageDialog(null, "Usuario já cadastrado");
             } else {
                  JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
             }   
        }
    }//GEN-LAST:event_btnCadastrarUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUsu;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox ckMostrarSenha;
    private javax.swing.JCheckBox ckMostrarSenhaUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelCadastroUsu;
    private java.awt.Panel painelUsuarioLogin;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JPasswordField pswUsu;
    private javax.swing.JTextField txtUsu;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
