/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.SistemaGestaoDao;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author welli
 */
public class ConfiguracoesUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracoesUsuarios
     */
    public ConfiguracoesUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListaUsu = new javax.swing.JButton();
        btnCadUsu = new javax.swing.JButton();
        btnAltUsu = new javax.swing.JButton();
        btnExcUsu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnListaUsu.setBackground(new java.awt.Color(51, 255, 255));
        btnListaUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lista-de-controle.png"))); // NOI18N
        btnListaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaUsu);
        btnListaUsu.setBounds(680, 60, 160, 140);

        btnCadUsu.setBackground(new java.awt.Color(51, 255, 255));
        btnCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro (1).png"))); // NOI18N
        btnCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadUsu);
        btnCadUsu.setBounds(80, 60, 160, 140);

        btnAltUsu.setBackground(new java.awt.Color(51, 255, 255));
        btnAltUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/conjunto-de-setas-de-sincronizacao.png"))); // NOI18N
        btnAltUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltUsu);
        btnAltUsu.setBounds(280, 60, 160, 140);

        btnExcUsu.setBackground(new java.awt.Color(51, 255, 255));
        btnExcUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btnExcUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcUsu);
        btnExcUsu.setBounds(480, 60, 160, 140);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("<HTML><CENTER>LISTAR<CENTER>  <P>USUARIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(720, 210, 100, 50);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("<HTML>CADASTRAR<CENTER>  <P>USUARIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 210, 120, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("<HTML>ALTERAR<CENTER>  <P>USUARIO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 210, 90, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("<HTML>EXCLUIR<CENTER>  <P>USUARIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 210, 80, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("CONFIGURAÇÕES DE USUARIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 10, 310, 40);

        setSize(new java.awt.Dimension(938, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuActionPerformed
new NovoUsuario().setVisible(true);        
    }//GEN-LAST:event_btnCadUsuActionPerformed

    private void btnAltUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltUsuActionPerformed
        String u;
      
       u = JOptionPane.showInputDialog(null, "Usuário a alterar: ");
       
       if(u == null){
            return;
        } else if(u.isEmpty()){
           JOptionPane.showMessageDialog(null, "Erro! Campo Vazio");
           return;
       }
       
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");
           
          PreparedStatement st = conectar.prepareStatement("SELECT * FROM  usuarios WHERE usuario = ?");
           st.setString(1, u);
           
            ResultSet usuario =  st.executeQuery(); // executa o select
           // 4 - Verificar se encontrou o usuario na tabela do BD
           if (usuario.next()){
               // 5 - Enviar os dados do usuário para a tela AlterarUsuarios
              String usu, sen;
              usu = usuario.getString("usuario");
              sen = usuario.getString("senha");
             
              
              new AlterarUsuario(usu, sen).setVisible(true);
              
              
           }else {
              JOptionPane.showMessageDialog(null, "Usuário não encontrado: ");
         }
           } catch (ClassNotFoundException | SQLException ex){
           JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
       }
        
        
        
    }//GEN-LAST:event_btnAltUsuActionPerformed

    private void btnExcUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcUsuActionPerformed
        String usuario;
        usuario = JOptionPane.showInputDialog("Digite o Nome do Usuario a Ser Excluído!");
        
         if(usuario == null){
            return;
        } 
       if(usuario.isEmpty()){
           JOptionPane.showMessageDialog(null, "Erro! Campo Vazio");
           return;
       }
        try {
             int retorno = new SistemaGestaoDao().excluirUsuario(usuario);
             
             if(retorno == 1){
                 JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
             
            }
                 
             
             
       } catch (ClassNotFoundException ex){
           JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
       } catch (SQLException ex){
           JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
       }
    }//GEN-LAST:event_btnExcUsuActionPerformed

    private void btnListaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaUsuActionPerformed
        new ListarUsuarios().setVisible(true);
    }//GEN-LAST:event_btnListaUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracoesUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltUsu;
    private javax.swing.JButton btnCadUsu;
    private javax.swing.JButton btnExcUsu;
    private javax.swing.JButton btnListaUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
