/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author welli
 */
public class ListarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ListarUsuarios
     */
    public ListarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNomeProdLista = new javax.swing.JLabel();
        txtBuscaUsu = new javax.swing.JTextField();
        btnBuscaUsu = new javax.swing.JButton();
        btnLimparcampo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("LISTA DE USUARIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 200, 40);

        btnNomeProdLista.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNomeProdLista.setText("USUARIO:");
        getContentPane().add(btnNomeProdLista);
        btnNomeProdLista.setBounds(30, 80, 90, 40);
        getContentPane().add(txtBuscaUsu);
        txtBuscaUsu.setBounds(120, 80, 250, 40);

        btnBuscaUsu.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscaUsu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBuscaUsu.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscaUsu.setText("BUSCAR");
        btnBuscaUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscaUsu);
        btnBuscaUsu.setBounds(380, 80, 130, 40);

        btnLimparcampo.setBackground(new java.awt.Color(0, 255, 204));
        btnLimparcampo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimparcampo.setForeground(new java.awt.Color(0, 0, 0));
        btnLimparcampo.setText("LIMPAR CAMPOS");
        btnLimparcampo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparcampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparcampoActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimparcampo);
        btnLimparcampo.setBounds(520, 80, 190, 40);

        tblUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "USUARIOS"
            }
        ));
        tblUsuarios.setRowHeight(40);
        jScrollPane1.setViewportView(tblUsuarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 680, 220);

        setSize(new java.awt.Dimension(739, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaUsuActionPerformed
        String nomeProd;
        nomeProd = txtBuscaUsu.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario LIKE ?");
            st.setString(1, "%" + nomeProd + "%");

            ResultSet usuarios = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblUsuarios.getModel();
            tblModelo.setRowCount(0);

            while(usuarios.next()){
                String linha[] = {
                    usuarios.getString("usuario"),
                   

                };
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscaUsuActionPerformed

    private void btnLimparcampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparcampoActionPerformed
        String nome;

        nome = txtBuscaUsu.getText();

        txtBuscaUsu.setText("");

    }//GEN-LAST:event_btnLimparcampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaUsu;
    private javax.swing.JButton btnLimparcampo;
    private javax.swing.JLabel btnNomeProdLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscaUsu;
    // End of variables declaration//GEN-END:variables
}
