/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.SistemaGestaoDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author welli
 */
public class ListarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form ListarProdutos
     */
    public ListarProdutos() {
        initComponents();
        listarProdutos();
    }
    
    private void listarProdutos(){
        try {
             ResultSet produtos = new SistemaGestaoDao().listarProdutos();
            
             
              DefaultTableModel tblModelo = (DefaultTableModel) tblProdutos.getModel();
              tblModelo.setRowCount(0);
              while(produtos.next()){
                  String linha[] = {
                      produtos.getString("cod_prod"),
                      produtos.getString("nomeProd"),
                      produtos.getString("qtd"),
                      
                  };
                  tblModelo.addRow(linha);
                  
              }
        } catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnNomeProdLista = new javax.swing.JLabel();
        txtBuscarProd = new javax.swing.JTextField();
        btnBuscarProd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("LISTA DE PRODUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 10, 210, 50);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        tblProdutos.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "QUANTIDADE"
            }
        ));
        tblProdutos.setRowHeight(30);
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 930, 340);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 150, 990, 380);

        btnNomeProdLista.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNomeProdLista.setText("NOME DO PRODUTO:");
        getContentPane().add(btnNomeProdLista);
        btnNomeProdLista.setBounds(10, 80, 200, 40);
        getContentPane().add(txtBuscarProd);
        txtBuscarProd.setBounds(210, 80, 300, 40);

        btnBuscarProd.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscarProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBuscarProd.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarProd.setText("BUSCAR");
        btnBuscarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarProd);
        btnBuscarProd.setBounds(520, 80, 130, 40);

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LIMPAR CAMPOS");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 80, 190, 40);

        setSize(new java.awt.Dimension(1026, 633));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        String nomeProd;
        nomeProd = txtBuscarProd.getText();
        
           try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");
           
             PreparedStatement st = conectar.prepareStatement("SELECT * FROM produtos WHERE nomeProd LIKE ?");
             st.setString(1, "%" + nomeProd + "%");
             
             ResultSet produtos = st.executeQuery();
             DefaultTableModel tblModelo = (DefaultTableModel) tblProdutos.getModel();
              tblModelo.setRowCount(0);
              
               while(produtos.next()){
                  String linha[] = {
                      produtos.getString("cod_prod"),
                      produtos.getString("nomeProd"),
                      produtos.getString("qtd"),
                    
                  };
                  tblModelo.addRow(linha);
                  
              }
             
             
             
           } catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }  
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome;

        nome = txtBuscarProd.getText();
       

        txtBuscarProd.setText("");
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JLabel btnNomeProdLista;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBuscarProd;
    // End of variables declaration//GEN-END:variables
}
