/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author welli
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundoLogin = new java.awt.Panel();
        painelUsuarioLogin = new java.awt.Panel();
        pswSenha = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        ckMostrarSenha = new javax.swing.JCheckBox();
        btnCadastrarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        painelFundoLogin.setBackground(new java.awt.Color(0, 102, 204));
        painelFundoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelFundoLogin.setName("_"); // NOI18N
        painelFundoLogin.setLayout(null);

        painelUsuarioLogin.setBackground(new java.awt.Color(255, 255, 255));
        painelUsuarioLogin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        painelUsuarioLogin.setLayout(null);

        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });
        pswSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswSenhaKeyPressed(evt);
            }
        });
        painelUsuarioLogin.add(pswSenha);
        pswSenha.setBounds(30, 150, 230, 30);

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        painelUsuarioLogin.add(txtUsuario);
        txtUsuario.setBounds(30, 70, 230, 30);

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuário");
        painelUsuarioLogin.add(lblUsuario);
        lblUsuario.setBounds(30, 30, 90, 40);

        btnEntrar.setBackground(new java.awt.Color(0, 204, 0));
        btnEntrar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setMnemonic('E');
        btnEntrar.setText("ENTRAR");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntrarKeyPressed(evt);
            }
        });
        painelUsuarioLogin.add(btnEntrar);
        btnEntrar.setBounds(80, 260, 120, 41);

        lblSenha.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha");
        painelUsuarioLogin.add(lblSenha);
        lblSenha.setBounds(30, 110, 71, 50);

        ckMostrarSenha.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        ckMostrarSenha.setForeground(new java.awt.Color(0, 0, 0));
        ckMostrarSenha.setText("Mostrar a senha");
        ckMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMostrarSenhaActionPerformed(evt);
            }
        });
        painelUsuarioLogin.add(ckMostrarSenha);
        ckMostrarSenha.setBounds(30, 190, 170, 28);

        btnCadastrarUsuario.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrarUsuario.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnCadastrarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrarUsuario.setText("CADASTRAR USUARIO");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });
        painelUsuarioLogin.add(btnCadastrarUsuario);
        btnCadastrarUsuario.setBounds(40, 310, 200, 40);

        painelFundoLogin.add(painelUsuarioLogin);
        painelUsuarioLogin.setBounds(10, 26, 290, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfil-de-usuario.png"))); // NOI18N
        painelFundoLogin.add(jLabel1);
        jLabel1.setBounds(380, 120, 160, 160);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelFundoLogin.add(jButton1);
        jButton1.setBounds(570, 0, 30, 30);

        getContentPane().add(painelFundoLogin);
        painelFundoLogin.setBounds(0, 0, 600, 430);

        setSize(new java.awt.Dimension(598, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenhaActionPerformed

    private void pswSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSenhaKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnEntrar.requestFocus();
        }
    }//GEN-LAST:event_pswSenhaKeyPressed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String usuario, senha;
        usuario = txtUsuario.getText();
        senha = pswSenha.getText();
        
        if(usuario.isEmpty() || senha.isEmpty()){
            JOptionPane.showMessageDialog(null, "[ERRO] Campos Vazios!");
        }else
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");
            
              PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario = ? AND senha = ?");
               st.setString(1, usuario);
               st.setString(2, senha);
               ResultSet usu = st.executeQuery();
               if(usu.next()){
                   new Menu().setVisible(true);
                    JOptionPane.showMessageDialog(null, "BEM-VINDO, " + usuario + "!");
                   dispose();
               }else {
                   JOptionPane.showMessageDialog(null, "[ERRO] Usúario ou Senha Inválidos");
               }
               
            
            
        } catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }  
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            btnEntrar.doClick(PROPERTIES);
        }

    }//GEN-LAST:event_btnEntrarKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed

        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            pswSenha.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void ckMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMostrarSenhaActionPerformed
        
        if(ckMostrarSenha.isSelected()){
            pswSenha.setEchoChar((char)0);
        }else {
            pswSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_ckMostrarSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        new CadastrarUsuario().setVisible(true);
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox ckMostrarSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private java.awt.Panel painelFundoLogin;
    private java.awt.Panel painelUsuarioLogin;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
