/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.SistemaGestaoDao;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonardo.ssouza38
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listarClientes();

    }

    private void historicoCompras() {
        String cpfCli;
        cpfCli = fmtCPFBuscar.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * from pedido where fk_cpf = ?");
            ResultSet clientes = st.executeQuery();
            st.setString(1, cpfCli);
            DefaultTableModel tblModelo = (DefaultTableModel) tblCompras.getModel();
            tblModelo.setRowCount(0);
            while (clientes.next()) {
                String linha[] = {
                    clientes.getString("cod_ped"),
                    clientes.getString("fk_cpf"),
                    clientes.getString("fk_cod_prod"),
                    clientes.getString("data_compra"),
                    clientes.getString("quant_compra")

                };
                tblModelo.addRow(linha);

            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }

    private void listarClientes() {

        try {
            ResultSet clientes = new SistemaGestaoDao().listarClientes();

            DefaultTableModel tblModelo = (DefaultTableModel) tblClientes.getModel();
            tblModelo.setRowCount(0);
            while (clientes.next()) {
                String linha[] = {
                    clientes.getString("Nome"),
                    clientes.getString("Sobrenome"),
                    clientes.getString("CPF"),
                    clientes.getString("Data_nasc"),
                    clientes.getString("Tel_fix"),
                    clientes.getString("Tel_cel"),
                    clientes.getString("Email")
                };
                tblModelo.addRow(linha);

            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        painelMenuGestaoCli = new javax.swing.JPanel();
        btnListarCli = new javax.swing.JButton();
        btnCadrastarCli = new javax.swing.JButton();
        btnAlterarCli = new javax.swing.JButton();
        btnExcluirCli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarCli = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        painelMenuLateral = new javax.swing.JPanel();
        btnGestaoClientes = new javax.swing.JButton();
        btnHistoricoCompras = new javax.swing.JButton();
        btnNovaCompra = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        lblHistoricoDeCompras = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        lblgestaoClientes = new javax.swing.JLabel();
        lblNovaCompra = new javax.swing.JLabel();
        painelCadastrarCliente = new javax.swing.JPanel();
        lblNomeCli = new javax.swing.JLabel();
        lblSobrenomeCli = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        fmtData = new javax.swing.JFormattedTextField();
        lblCPF = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        fmtCPF = new javax.swing.JFormattedTextField();
        lblSexo = new javax.swing.JLabel();
        cmbSexoBiologico = new javax.swing.JComboBox<>();
        lblGenero = new javax.swing.JLabel();
        cmbIdentidadeDeGenero = new javax.swing.JComboBox<>();
        lblNomeSocial = new javax.swing.JLabel();
        txtNomeSocial = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtFixo = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        lblCelular = new javax.swing.JLabel();
        lblTelFixo = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        btnCancelarCadastro = new javax.swing.JButton();
        lblDadosPessoais = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCadastrarCliente1 = new javax.swing.JButton();
        lblTituloCadastro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnConfigUsuario = new javax.swing.JButton();
        painelListarClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblNomeCliBuscar = new javax.swing.JLabel();
        txtNomeBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        painelHistorico = new javax.swing.JPanel();
        lblCPFBuscar = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        btnLimparCampo = new javax.swing.JButton();
        fmtCPFBuscar = new javax.swing.JFormattedTextField();
        painelNovaCompra = new javax.swing.JPanel();
        lblCPFCli = new javax.swing.JLabel();
        fmtCPFCliNovaCompra = new javax.swing.JFormattedTextField();
        btnConfirmarProduto = new javax.swing.JButton();
        lblCPFCli1 = new javax.swing.JLabel();
        btnBuscarProdNovaCompra = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNovaCompraCli = new javax.swing.JTable();
        txtNomeProdNovaCompra = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNovaCompraProd = new javax.swing.JTable();
        btnConfirmarCliNovaCOmpra = new javax.swing.JButton();
        btnBuscarCli1NovaCompra = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        painelPedido = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNomeCliPedido = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNomeProdPedido = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtQtdProdutoPedido = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCPFCliPedidoNovaCompra = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCodProdPedido = new javax.swing.JTextField();
        btnRealizarCompra = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        painelProdutos = new javax.swing.JPanel();
        btnListarProduto = new javax.swing.JButton();
        btnAddProduto = new javax.swing.JButton();
        btnAltProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel19.setText("jLabel19");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Clientes");
        setBackground(new java.awt.Color(0, 102, 204));
        setExtendedState(MAXIMIZED_BOTH);
        setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        painelMenuGestaoCli.setBackground(new java.awt.Color(0, 102, 204));
        painelMenuGestaoCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        painelMenuGestaoCli.setVisible(false);
        painelMenuGestaoCli.setEnabled(false);
        painelMenuGestaoCli.setLayout(null);

        btnListarCli.setBackground(new java.awt.Color(255, 255, 255));
        btnListarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lista-de-controle.png"))); // NOI18N
        btnListarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCliActionPerformed(evt);
            }
        });
        painelMenuGestaoCli.add(btnListarCli);
        btnListarCli.setBounds(700, 20, 150, 140);

        btnCadrastarCli.setBackground(new java.awt.Color(255, 255, 255));
        btnCadrastarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro (1).png"))); // NOI18N
        btnCadrastarCli.setToolTipText("");
        btnCadrastarCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCadrastarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadrastarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadrastarCliActionPerformed(evt);
            }
        });
        painelMenuGestaoCli.add(btnCadrastarCli);
        btnCadrastarCli.setBounds(60, 20, 150, 140);

        btnAlterarCli.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/conjunto-de-setas-de-sincronizacao.png"))); // NOI18N
        btnAlterarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCliActionPerformed(evt);
            }
        });
        painelMenuGestaoCli.add(btnAlterarCli);
        btnAlterarCli.setBounds(270, 20, 150, 140);

        btnExcluirCli.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btnExcluirCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCliActionPerformed(evt);
            }
        });
        painelMenuGestaoCli.add(btnExcluirCli);
        btnExcluirCli.setBounds(480, 20, 150, 140);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><center>BUSCAR <br><center>CLIENTE");
        painelMenuGestaoCli.add(jLabel1);
        jLabel1.setBounds(930, 170, 120, 50);

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html><center>CADASTRAR <br><center>CLIENTE");
        painelMenuGestaoCli.add(jLabel2);
        jLabel2.setBounds(60, 170, 140, 50);

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html><center>ALTERAR <br><center>DADOS\n");
        painelMenuGestaoCli.add(jLabel6);
        jLabel6.setBounds(290, 170, 110, 50);

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html><center>EXCLUIR <br><center>CLIENTE");
        painelMenuGestaoCli.add(jLabel7);
        jLabel7.setBounds(500, 170, 110, 50);

        btnBuscarCli.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/marketing-de-busca.png"))); // NOI18N
        btnBuscarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliActionPerformed(evt);
            }
        });
        painelMenuGestaoCli.add(btnBuscarCli);
        btnBuscarCli.setBounds(910, 20, 150, 140);

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><center>LISTAR <br><center>CLIENTES");
        painelMenuGestaoCli.add(jLabel3);
        jLabel3.setBounds(720, 170, 120, 50);

        getContentPane().add(painelMenuGestaoCli);
        painelMenuGestaoCli.setBounds(330, 130, 1110, 250);

        painelMenuLateral.setBackground(new java.awt.Color(0, 102, 204));
        painelMenuLateral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        painelMenuLateral.setLayout(null);

        btnGestaoClientes.setBackground(new java.awt.Color(0, 255, 0));
        btnGestaoClientes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGestaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/equipe.png"))); // NOI18N
        btnGestaoClientes.setToolTipText("Cadastrar, Alterar e Excluir clientes");
        btnGestaoClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGestaoClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestaoClientesActionPerformed(evt);
            }
        });
        painelMenuLateral.add(btnGestaoClientes);
        btnGestaoClientes.setBounds(30, 20, 190, 130);

        btnHistoricoCompras.setBackground(new java.awt.Color(255, 204, 102));
        btnHistoricoCompras.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnHistoricoCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/historia.png"))); // NOI18N
        btnHistoricoCompras.setToolTipText("Exibe o Histórico do Cliente Pesquisado");
        btnHistoricoCompras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnHistoricoCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistoricoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoComprasActionPerformed(evt);
            }
        });
        painelMenuLateral.add(btnHistoricoCompras);
        btnHistoricoCompras.setBounds(30, 200, 190, 130);

        btnNovaCompra.setBackground(new java.awt.Color(102, 102, 255));
        btnNovaCompra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnNovaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sacolas-de-compras.png"))); // NOI18N
        btnNovaCompra.setToolTipText("Crie Promoções e Envie Aos Seus Clientes");
        btnNovaCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNovaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCompraActionPerformed(evt);
            }
        });
        painelMenuLateral.add(btnNovaCompra);
        btnNovaCompra.setBounds(30, 400, 190, 140);

        btnProdutos.setBackground(new java.awt.Color(255, 51, 51));
        btnProdutos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar-ao-carrinho.png"))); // NOI18N
        btnProdutos.setToolTipText("Envie e-mails e mensagens aos clientes");
        btnProdutos.setActionCommand("\n");
        btnProdutos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        painelMenuLateral.add(btnProdutos);
        btnProdutos.setBounds(30, 600, 190, 140);

        lblHistoricoDeCompras.setBackground(new java.awt.Color(255, 255, 255));
        lblHistoricoDeCompras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHistoricoDeCompras.setForeground(new java.awt.Color(255, 255, 255));
        lblHistoricoDeCompras.setText("<HTML><CENTER>HISTÓRICO <BR>DE COMPRAS");
        painelMenuLateral.add(lblHistoricoDeCompras);
        lblHistoricoDeCompras.setBounds(60, 330, 140, 60);

        lblProdutos.setBackground(new java.awt.Color(255, 255, 255));
        lblProdutos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lblProdutos.setText("PRODUTOS");
        painelMenuLateral.add(lblProdutos);
        lblProdutos.setBounds(70, 740, 110, 30);

        lblgestaoClientes.setBackground(new java.awt.Color(0, 0, 0));
        lblgestaoClientes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblgestaoClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblgestaoClientes.setText("GESTÃO DE CLIENTES");
        painelMenuLateral.add(lblgestaoClientes);
        lblgestaoClientes.setBounds(30, 150, 200, 30);

        lblNovaCompra.setBackground(new java.awt.Color(255, 255, 255));
        lblNovaCompra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNovaCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblNovaCompra.setText("NOVA COMPRA");
        painelMenuLateral.add(lblNovaCompra);
        lblNovaCompra.setBounds(60, 540, 140, 30);

        getContentPane().add(painelMenuLateral);
        painelMenuLateral.setBounds(30, 130, 250, 820);

        painelCadastrarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        painelCadastrarCliente.setEnabled(false);
        painelCadastrarCliente.setVisible(false);
        painelCadastrarCliente.setLayout(null);

        lblNomeCli.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNomeCli.setText("NOME:");
        painelCadastrarCliente.add(lblNomeCli);
        lblNomeCli.setBounds(130, 110, 80, 40);

        lblSobrenomeCli.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblSobrenomeCli.setText("SOBRENOME:");
        painelCadastrarCliente.add(lblSobrenomeCli);
        lblSobrenomeCli.setBounds(490, 110, 140, 40);

        txtSobrenome.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        painelCadastrarCliente.add(txtSobrenome);
        txtSobrenome.setBounds(630, 110, 280, 40);

        lblData.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblData.setText("NASCIMENTO:");
        painelCadastrarCliente.add(lblData);
        lblData.setBounds(60, 170, 140, 40);

        try {
            fmtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtData.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fmtData.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        painelCadastrarCliente.add(fmtData);
        fmtData.setBounds(210, 170, 130, 40);

        lblCPF.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblCPF.setText("CPF:");
        painelCadastrarCliente.add(lblCPF);
        lblCPF.setBounds(570, 174, 50, 30);

        txtNome.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtNome.setToolTipText("");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        painelCadastrarCliente.add(txtNome);
        txtNome.setBounds(210, 110, 260, 40);

        try {
            fmtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtCPF.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        painelCadastrarCliente.add(fmtCPF);
        fmtCPF.setBounds(630, 170, 200, 40);

        lblSexo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblSexo.setText("SEXO:");
        painelCadastrarCliente.add(lblSexo);
        lblSexo.setBounds(130, 220, 70, 40);

        cmbSexoBiologico.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cmbSexoBiologico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO", "INTERSEXO", "PREFIRO NÃO INFORMAR", " " }));
        cmbSexoBiologico.setToolTipText("");
        painelCadastrarCliente.add(cmbSexoBiologico);
        cmbSexoBiologico.setBounds(210, 220, 260, 40);

        lblGenero.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblGenero.setText("GÊNERO:");
        painelCadastrarCliente.add(lblGenero);
        lblGenero.setBounds(100, 290, 100, 30);

        cmbIdentidadeDeGenero.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cmbIdentidadeDeGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CISGENERO ", "TRANSGENERO", "NÃO BINÁRIO", "PREFIRO NÃO INFORMAR", " " }));
        cmbIdentidadeDeGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdentidadeDeGeneroActionPerformed(evt);
            }
        });
        painelCadastrarCliente.add(cmbIdentidadeDeGenero);
        cmbIdentidadeDeGenero.setBounds(210, 280, 260, 40);

        lblNomeSocial.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNomeSocial.setText("NOME SOCIAL:");
        painelCadastrarCliente.add(lblNomeSocial);
        lblNomeSocial.setBounds(50, 350, 150, 24);

        txtNomeSocial.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        painelCadastrarCliente.add(txtNomeSocial);
        txtNomeSocial.setBounds(210, 340, 260, 40);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        painelCadastrarCliente.add(txtEmail);
        txtEmail.setBounds(220, 570, 360, 40);

        lblEmail.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblEmail.setText("EMAIL:");
        painelCadastrarCliente.add(lblEmail);
        lblEmail.setBounds(120, 570, 80, 40);

        try {
            txtFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFixo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        painelCadastrarCliente.add(txtFixo);
        txtFixo.setBounds(220, 490, 210, 40);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        painelCadastrarCliente.add(txtCelular);
        txtCelular.setBounds(640, 490, 220, 40);

        lblCelular.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblCelular.setText("CELULAR:");
        painelCadastrarCliente.add(lblCelular);
        lblCelular.setBounds(530, 490, 100, 40);

        lblTelFixo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblTelFixo.setText("TELEFONE FIXO:");
        painelCadastrarCliente.add(lblTelFixo);
        lblTelFixo.setBounds(40, 490, 170, 40);

        lblContato.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lblContato.setText("CONTATO:");
        painelCadastrarCliente.add(lblContato);
        lblContato.setBounds(30, 430, 120, 30);

        btnCancelarCadastro.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarCadastro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCancelarCadastro.setText("CANCELAR");
        btnCancelarCadastro.setToolTipText("Limpa os Dados Digitados e Retorna ao Menu Anterior");
        btnCancelarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadastroActionPerformed(evt);
            }
        });
        painelCadastrarCliente.add(btnCancelarCadastro);
        btnCancelarCadastro.setBounds(370, 750, 160, 50);

        lblDadosPessoais.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lblDadosPessoais.setText("DADOS PESSOAIS:");
        painelCadastrarCliente.add(lblDadosPessoais);
        lblDadosPessoais.setBounds(20, 60, 220, 40);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator1.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        painelCadastrarCliente.add(jSeparator1);
        jSeparator1.setBounds(0, 400, 930, 10);

        btnCadastrarCliente1.setBackground(new java.awt.Color(0, 153, 0));
        btnCadastrarCliente1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCadastrarCliente1.setText("CADASTRAR");
        btnCadastrarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCliente1ActionPerformed(evt);
            }
        });
        painelCadastrarCliente.add(btnCadastrarCliente1);
        btnCadastrarCliente1.setBounds(340, 680, 220, 60);

        lblTituloCadastro.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblTituloCadastro.setForeground(new java.awt.Color(0, 0, 255));
        lblTituloCadastro.setText("CADASTRO DO CLIENTE");
        painelCadastrarCliente.add(lblTituloCadastro);
        lblTituloCadastro.setBounds(300, 1, 270, 40);

        getContentPane().add(painelCadastrarCliente);
        painelCadastrarCliente.setBounds(330, 130, 930, 820);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(null);

        btnConfigUsuario.setBackground(new java.awt.Color(153, 153, 153));
        btnConfigUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracoes.png"))); // NOI18N
        btnConfigUsuario.setToolTipText("Configurações de Usuarios\n");
        btnConfigUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnConfigUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfigUsuario);
        btnConfigUsuario.setBounds(40, 10, 90, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 10, 1880, 110);

        painelListarClientes.setBackground(new java.awt.Color(255, 255, 255));
        painelListarClientes.setVisible(false);
        painelListarClientes.setEnabled(false);
        painelListarClientes.setLayout(null);

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        tblClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblClientes.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "SOBRENOME", "CPF", "NASCIMENTO", "TELEFONE FIXO", "CELULAR", "EMAIL"
            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClientes.setRowHeight(40);
        tblClientes.setRowSelectionAllowed(false);
        tblClientes.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setMinWidth(150);
            tblClientes.getColumnModel().getColumn(0).setMaxWidth(150);
            tblClientes.getColumnModel().getColumn(1).setMinWidth(200);
            tblClientes.getColumnModel().getColumn(1).setMaxWidth(400);
            tblClientes.getColumnModel().getColumn(2).setMinWidth(150);
            tblClientes.getColumnModel().getColumn(2).setMaxWidth(150);
            tblClientes.getColumnModel().getColumn(3).setMinWidth(150);
            tblClientes.getColumnModel().getColumn(3).setMaxWidth(150);
            tblClientes.getColumnModel().getColumn(4).setMinWidth(150);
            tblClientes.getColumnModel().getColumn(4).setMaxWidth(150);
            tblClientes.getColumnModel().getColumn(5).setMinWidth(200);
            tblClientes.getColumnModel().getColumn(5).setMaxWidth(200);
            tblClientes.getColumnModel().getColumn(6).setMinWidth(200);
            tblClientes.getColumnModel().getColumn(6).setMaxWidth(400);
        }

        painelListarClientes.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 1360, 590);

        lblNomeCliBuscar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblNomeCliBuscar.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeCliBuscar.setText("NOME:");
        painelListarClientes.add(lblNomeCliBuscar);
        lblNomeCliBuscar.setBounds(30, 100, 80, 40);

        txtNomeBuscar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtNomeBuscar.setToolTipText("");
        txtNomeBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeBuscarActionPerformed(evt);
            }
        });
        painelListarClientes.add(txtNomeBuscar);
        txtNomeBuscar.setBounds(110, 100, 280, 40);

        btnBuscar.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        painelListarClientes.add(btnBuscar);
        btnBuscar.setBounds(410, 100, 112, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("LISTA DE CLIENTES");
        painelListarClientes.add(jLabel4);
        jLabel4.setBounds(550, 20, 300, 40);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelListarClientes.add(jButton1);
        jButton1.setBounds(1370, 0, 30, 30);

        getContentPane().add(painelListarClientes);
        painelListarClientes.setBounds(300, 130, 1400, 820);

        painelHistorico.setBackground(new java.awt.Color(255, 255, 255));
        painelHistorico.setVisible(false);
        painelHistorico.setEnabled(false);
        painelHistorico.setLayout(null);

        lblCPFBuscar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCPFBuscar.setForeground(new java.awt.Color(0, 0, 0));
        lblCPFBuscar.setText("CPF:");
        painelHistorico.add(lblCPFBuscar);
        lblCPFBuscar.setBounds(30, 120, 50, 40);

        btnBuscar1.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscar1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("BUSCAR");
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        painelHistorico.add(btnBuscar1);
        btnBuscar1.setBounds(390, 120, 112, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("HISTÓRICO DE COMPRAS");
        painelHistorico.add(jLabel5);
        jLabel5.setBounds(510, 10, 280, 50);

        tblCompras.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOME CLIENTE", "PRODUTO", "DATA DA COMPRA", "QUANTIDADE"
            }
        ));
        tblCompras.setRowHeight(40);
        jScrollPane2.setViewportView(tblCompras);

        painelHistorico.add(jScrollPane2);
        jScrollPane2.setBounds(30, 190, 1340, 590);

        btnLimparCampo.setBackground(new java.awt.Color(0, 153, 255));
        btnLimparCampo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnLimparCampo.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparCampo.setText("LIMPAR CAMPO");
        btnLimparCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCampoActionPerformed(evt);
            }
        });
        painelHistorico.add(btnLimparCampo);
        btnLimparCampo.setBounds(530, 120, 190, 40);

        try {
            fmtCPFBuscar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtCPFBuscar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        fmtCPFBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fmtCPFBuscarMouseClicked(evt);
            }
        });
        fmtCPFBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmtCPFBuscarActionPerformed(evt);
            }
        });
        painelHistorico.add(fmtCPFBuscar);
        fmtCPFBuscar.setBounds(90, 120, 260, 40);

        getContentPane().add(painelHistorico);
        painelHistorico.setBounds(300, 130, 1410, 820);

        painelNovaCompra.setBackground(new java.awt.Color(255, 255, 255));
        painelNovaCompra.setVisible(false);
        painelNovaCompra.setEnabled(false);
        painelPedido.setVisible(false);
        painelPedido.setEnabled(false);

        painelNovaCompra.setLayout(null);

        lblCPFCli.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCPFCli.setForeground(new java.awt.Color(0, 0, 0));
        lblCPFCli.setText("CPF DO CLIENTE:");
        painelNovaCompra.add(lblCPFCli);
        lblCPFCli.setBounds(70, 120, 160, 30);

        try {
            fmtCPFCliNovaCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtCPFCliNovaCompra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fmtCPFCliNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmtCPFCliNovaCompraActionPerformed(evt);
            }
        });
        painelNovaCompra.add(fmtCPFCliNovaCompra);
        fmtCPFCliNovaCompra.setBounds(240, 120, 210, 30);

        btnConfirmarProduto.setBackground(new java.awt.Color(51, 51, 255));
        btnConfirmarProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarProduto.setText("CONFIRMAR PRODUTO");
        btnConfirmarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarProdutoActionPerformed(evt);
            }
        });
        painelNovaCompra.add(btnConfirmarProduto);
        btnConfirmarProduto.setBounds(700, 250, 200, 30);

        lblCPFCli1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCPFCli1.setForeground(new java.awt.Color(0, 0, 0));
        lblCPFCli1.setText("NOME DO PRODUTO:");
        painelNovaCompra.add(lblCPFCli1);
        lblCPFCli1.setBounds(70, 260, 200, 22);

        btnBuscarProdNovaCompra.setBackground(new java.awt.Color(0, 255, 0));
        btnBuscarProdNovaCompra.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarProdNovaCompra.setText("BUSCAR");
        btnBuscarProdNovaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProdNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdNovaCompraActionPerformed(evt);
            }
        });
        painelNovaCompra.add(btnBuscarProdNovaCompra);
        btnBuscarProdNovaCompra.setBounds(460, 250, 120, 30);

        tblNovaCompraCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "CPF", "NOME", "SOBRENOME"
            }
        ));
        tblNovaCompraCli.setRowHeight(40);
        tblNovaCompraCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNovaCompraCliMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNovaCompraCli);

        painelNovaCompra.add(jScrollPane3);
        jScrollPane3.setBounds(60, 170, 840, 60);
        painelNovaCompra.add(txtNomeProdNovaCompra);
        txtNomeProdNovaCompra.setBounds(260, 250, 190, 30);

        tblNovaCompraProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "QUANTIDADE"
            }
        ));
        tblNovaCompraProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNovaCompraProdMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblNovaCompraProd);

        painelNovaCompra.add(jScrollPane4);
        jScrollPane4.setBounds(60, 310, 840, 80);

        btnConfirmarCliNovaCOmpra.setBackground(new java.awt.Color(51, 51, 255));
        btnConfirmarCliNovaCOmpra.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarCliNovaCOmpra.setText("CONFIRMAR CLIENTE");
        btnConfirmarCliNovaCOmpra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCliNovaCOmpra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCliNovaCOmpraActionPerformed(evt);
            }
        });
        painelNovaCompra.add(btnConfirmarCliNovaCOmpra);
        btnConfirmarCliNovaCOmpra.setBounds(700, 120, 200, 30);

        btnBuscarCli1NovaCompra.setBackground(new java.awt.Color(0, 204, 0));
        btnBuscarCli1NovaCompra.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarCli1NovaCompra.setText("BUSCAR");
        btnBuscarCli1NovaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCli1NovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCli1NovaCompraActionPerformed(evt);
            }
        });
        painelNovaCompra.add(btnBuscarCli1NovaCompra);
        btnBuscarCli1NovaCompra.setBounds(460, 120, 120, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("NOVA COMPRA");
        painelNovaCompra.add(jLabel12);
        jLabel12.setBounds(380, 30, 160, 30);

        painelPedido.setBackground(new java.awt.Color(204, 0, 255));
        painelNovaCompra.setVisible(false);
        painelNovaCompra.setEnabled(false);

        painelPedido.setVisible(false);
        painelPedido.setEnabled(false);
        painelPedido.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PEDIDO:");
        painelPedido.add(jLabel13);
        jLabel13.setBounds(370, 0, 80, 40);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NOME:");
        painelPedido.add(jLabel14);
        jLabel14.setBounds(460, 50, 70, 40);
        painelPedido.add(txtNomeCliPedido);
        txtNomeCliPedido.setBounds(540, 50, 210, 40);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PRODUTO:");
        painelPedido.add(jLabel15);
        jLabel15.setBounds(420, 110, 110, 40);

        txtNomeProdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdPedidoActionPerformed(evt);
            }
        });
        painelPedido.add(txtNomeProdPedido);
        txtNomeProdPedido.setBounds(540, 110, 210, 40);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("QUANTIDADE:");
        painelPedido.add(jLabel16);
        jLabel16.setBounds(250, 170, 140, 40);

        txtQtdProdutoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdProdutoPedidoActionPerformed(evt);
            }
        });
        painelPedido.add(txtQtdProdutoPedido);
        txtQtdProdutoPedido.setBounds(410, 170, 210, 40);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CPF:");
        painelPedido.add(jLabel17);
        jLabel17.setBounds(130, 50, 50, 40);
        painelPedido.add(txtCPFCliPedidoNovaCompra);
        txtCPFCliPedidoNovaCompra.setBounds(190, 50, 210, 40);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CÓDIGO:");
        painelPedido.add(jLabel18);
        jLabel18.setBounds(100, 110, 80, 40);

        txtCodProdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdPedidoActionPerformed(evt);
            }
        });
        painelPedido.add(txtCodProdPedido);
        txtCodProdPedido.setBounds(190, 110, 210, 40);

        btnRealizarCompra.setBackground(new java.awt.Color(0, 204, 0));
        btnRealizarCompra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRealizarCompra.setForeground(new java.awt.Color(0, 0, 0));
        btnRealizarCompra.setText("FINALIZAR COMPRA");
        btnRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarCompraActionPerformed(evt);
            }
        });
        painelPedido.add(btnRealizarCompra);
        btnRealizarCompra.setBounds(190, 240, 230, 50);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        painelPedido.add(jButton2);
        jButton2.setBounds(500, 240, 130, 50);

        painelNovaCompra.add(painelPedido);
        painelPedido.setBounds(60, 420, 840, 300);

        getContentPane().add(painelNovaCompra);
        painelNovaCompra.setBounds(270, 180, 1020, 740);

        painelProdutos.setBackground(new java.awt.Color(255, 51, 51));
        painelProdutos.setForeground(new java.awt.Color(255, 255, 255));
        painelProdutos.setVisible(false);
        painelProdutos.setEnabled(false);
        painelProdutos.setLayout(null);

        btnListarProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnListarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listaProdutos.png"))); // NOI18N
        btnListarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdutoActionPerformed(evt);
            }
        });
        painelProdutos.add(btnListarProduto);
        btnListarProduto.setBounds(860, 30, 150, 150);

        btnAddProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar-produto.png"))); // NOI18N
        btnAddProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });
        painelProdutos.add(btnAddProduto);
        btnAddProduto.setBounds(60, 30, 150, 150);

        btnAltProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnAltProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterarProduto.png"))); // NOI18N
        btnAltProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltProdutoActionPerformed(evt);
            }
        });
        painelProdutos.add(btnAltProduto);
        btnAltProduto.setBounds(330, 30, 150, 150);

        btnExcluirProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir-produto.png"))); // NOI18N
        btnExcluirProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });
        painelProdutos.add(btnExcluirProduto);
        btnExcluirProduto.setBounds(600, 30, 150, 150);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><center> LISTAR <p>PRODUTOS");
        painelProdutos.add(jLabel8);
        jLabel8.setBounds(880, 190, 110, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html><center> ADICIONAR <p>PRODUTO");
        painelProdutos.add(jLabel9);
        jLabel9.setBounds(80, 190, 110, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("<html><center> ALTERAR <p>PRODUTO");
        painelProdutos.add(jLabel10);
        jLabel10.setBounds(360, 190, 100, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<html><center> EXCLUIR <p>PRODUTO");
        painelProdutos.add(jLabel11);
        jLabel11.setBounds(630, 190, 100, 40);

        getContentPane().add(painelProdutos);
        painelProdutos.setBounds(330, 130, 1110, 250);

        setSize(new java.awt.Dimension(1936, 1088));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void verificarEnable() {
        if (painelCadastrarCliente.isEnabled() || painelMenuGestaoCli.isEnabled() || painelListarClientes.isEnabled() || painelHistorico.isEnabled() || painelProdutos.isEnabled() || (painelNovaCompra.isEnabled() && painelPedido.isEnabled())) {
            fecharCadastrarCliente();
            fecharMenuGestaoCli();
            fecharListarClientes();
            fecharHistorico();
            fecharProdutos();
            fecharNovaCompra();
            fecharPedido();

        }

    }

    private void mostrarCadastrarCliente() {
        verificarEnable();
        painelCadastrarCliente.setEnabled(true);
        painelCadastrarCliente.setVisible(true);
    }

    private void fecharCadastrarCliente() {
        painelCadastrarCliente.setEnabled(false);
        painelCadastrarCliente.setVisible(false);
    }

    private void mostrarMenuGestaoCli() {
        verificarEnable();
        painelMenuGestaoCli.setEnabled(true);
        painelMenuGestaoCli.setVisible(true);
    }

    private void fecharMenuGestaoCli() {
        painelMenuGestaoCli.setEnabled(false);
        painelMenuGestaoCli.setVisible(false);
    }

    private void mostrarListarClientes() {
        verificarEnable();
        painelListarClientes.setEnabled(true);
        painelListarClientes.setVisible(true);
    }

    private void fecharListarClientes() {
        painelListarClientes.setEnabled(false);
        painelListarClientes.setVisible(false);
    }

    private void mostrarHistorico() {
        verificarEnable();
        painelHistorico.setEnabled(true);
        painelHistorico.setVisible(true);
    }

    private void fecharHistorico() {
        painelHistorico.setEnabled(false);
        painelHistorico.setVisible(false);
    }

    private void mostrarProdutos() {
        verificarEnable();
        painelProdutos.setEnabled(true);
        painelProdutos.setVisible(true);
    }

    private void fecharProdutos() {
        painelProdutos.setEnabled(false);
        painelProdutos.setVisible(false);
    }

    private void mostrarNovaCompra() {
        verificarEnable();
        painelNovaCompra.setEnabled(true);
        painelNovaCompra.setVisible(true);
    }

    private void fecharNovaCompra() {
        painelNovaCompra.setEnabled(false);
        painelNovaCompra.setVisible(false);
    }

    private void mostrarPedido() {
        verificarEnable();
        painelPedido.setEnabled(true);
        painelPedido.setVisible(true);
    }

    private void fecharPedido() {
        painelPedido.setEnabled(false);
        painelPedido.setVisible(false);
    }


    private void btnGestaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestaoClientesActionPerformed
        if (painelMenuGestaoCli.isEnabled()) {
            fecharMenuGestaoCli();

        } else {
            mostrarMenuGestaoCli();

        }
    }//GEN-LAST:event_btnGestaoClientesActionPerformed

    private void btnHistoricoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoComprasActionPerformed
        if (painelHistorico.isEnabled()) {
            fecharHistorico();
        } else {
            mostrarHistorico();
        }

    }//GEN-LAST:event_btnHistoricoComprasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        if (painelProdutos.isEnabled()) {
            fecharProdutos();
        } else {
            mostrarProdutos();
        }
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadastroActionPerformed
        if (painelMenuGestaoCli.isEnabled()) {
            fecharMenuGestaoCli();
        } else {
            mostrarMenuGestaoCli();
        }
        txtNome.setText("");
        txtSobrenome.setText("");
        txtNomeSocial.setText("");
        txtFixo.setText("");
        txtEmail.setText("");
        txtCelular.setText("");
        fmtData.setText("");
        fmtCPF.setText("");

    }//GEN-LAST:event_btnCancelarCadastroActionPerformed

    private void cmbIdentidadeDeGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdentidadeDeGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIdentidadeDeGeneroActionPerformed

    private void btnCadrastarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadrastarCliActionPerformed
        if (painelCadastrarCliente.isEnabled()) {
            fecharCadastrarCliente();
        } else {
            mostrarCadastrarCliente();
        }


    }//GEN-LAST:event_btnCadrastarCliActionPerformed

    private void btnCadastrarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCliente1ActionPerformed
        String nomeCli, sobrenomeCli, cpfCli, dataNascCli, sexoCli, generoCli, nomeSocialCli, telFixoCli, celularCli, emailCli;

        nomeCli = txtNome.getText();
        sobrenomeCli = txtSobrenome.getText();
        dataNascCli = fmtData.getText();
        cpfCli = fmtCPF.getText();
        sexoCli = cmbSexoBiologico.getSelectedItem().toString();
        generoCli = cmbIdentidadeDeGenero.getSelectedItem().toString();
        nomeSocialCli = txtNomeSocial.getText();
        telFixoCli = txtFixo.getText();
        celularCli = txtCelular.getText();
        emailCli = txtEmail.getText();
        if (nomeCli.isEmpty() || sobrenomeCli.isEmpty() || dataNascCli.isEmpty() || cpfCli.isEmpty()) {
            JOptionPane.showMessageDialog(null, "[ERRO] Existem Campos Vazios!");
        } else
         try {
            new SistemaGestaoDao().cadastrarCliente(nomeCli, sobrenomeCli, dataNascCli, cpfCli, sexoCli, generoCli, nomeSocialCli, telFixoCli, celularCli, emailCli);
            JOptionPane.showMessageDialog(null, "Cliente Cadastrado com Sucesso");
            txtNome.setText("");
            txtSobrenome.setText("");
            fmtCPF.setText("");
            fmtData.setText("");
            txtNomeSocial.setText("");
            txtFixo.setText("");
            txtEmail.setText("");
            txtCelular.setText("");
            fmtData.setText("");
            fmtCPF.setText("");

            listarClientes();

        } catch (ClassNotFoundException | SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado");
            }
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnCadastrarCliente1ActionPerformed

    private void btnListarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCliActionPerformed
        if (painelListarClientes.isEnabled()) {
            fecharListarClientes();
        } else {
            mostrarListarClientes();
            listarClientes();

        }


    }//GEN-LAST:event_btnListarCliActionPerformed

    private void btnAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCliActionPerformed

        String cpfCliente;
        cpfCliente = JOptionPane.showInputDialog("Informe o CPF do Cliente a Alterar:  ");
        if (cpfCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "[ERRO] Nenhum CPF Informado!");
        } else 
        
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM clientes WHERE cpf = ?");
            st.setString(1, cpfCliente);

            ResultSet cliente = st.executeQuery();

            if (cliente.next()) {
                String nomeCli, sobrenomeCli, cpfCli, dataNascCli, sexoCli, generoCli, nomeSocialCli, telFixoCli, celularCli, emailCli;
                nomeCli = cliente.getString("nome");
                sobrenomeCli = cliente.getString("sobrenome");
                cpfCli = cliente.getString("cpf");
                dataNascCli = cliente.getString("data_nasc");
                sexoCli = cliente.getString("sexo");
                generoCli = cliente.getString("genero");
                nomeSocialCli = cliente.getString("nome_social");
                telFixoCli = cliente.getString("tel_fix");
                celularCli = cliente.getString("tel_cel");
                emailCli = cliente.getString("email");

                new AlterarDados(nomeCli, sobrenomeCli, cpfCli, dataNascCli, sexoCli, generoCli, nomeSocialCli, telFixoCli, celularCli, emailCli).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Cliente Não Encontrado! ");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnAlterarCliActionPerformed

    private void btnBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliActionPerformed
        String cpfCliente;
        cpfCliente = JOptionPane.showInputDialog("Informe o CPF do Cliente a Alterar:  ");

        if (cpfCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "[ERRO] Nenhum CPF Informado!");
        } else 
        
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM clientes WHERE cpf = ?");
            st.setString(1, cpfCliente);

            ResultSet cliente = st.executeQuery();

            if (cliente.next()) {
                String nomeCli, sobrenomeCli, cpfCli, dataNascCli, sexoCli, generoCli, nomeSocialCli, telFixoCli, celularCli, emailCli;
                nomeCli = cliente.getString("nome");
                sobrenomeCli = cliente.getString("sobrenome");
                cpfCli = cliente.getString("cpf");
                dataNascCli = cliente.getString("data_nasc");
                sexoCli = cliente.getString("sexo");
                generoCli = cliente.getString("genero");
                nomeSocialCli = cliente.getString("nome_social");
                telFixoCli = cliente.getString("tel_fix");
                celularCli = cliente.getString("tel_cel");
                emailCli = cliente.getString("email");

                /*   JOptionPane.showMessageDialog(null, 
                           "Nome Completo: " + nomeCli + " " + sobrenomeCli + "\n" + 
                           "CPF: " + cpfCli + "\n" + 
                           "Data De Nascimento: " + dataNascCli + "\n" +
                           "Sexo: " + sexoCli + "\n" +
                           "Genero: " + generoCli + "\n" +
                           "Nome Social: " + nomeSocialCli + "\n" +
                           "Telefone Fixo: " + telFixoCli + "\n" +
                           "Telefone Celular: " + celularCli + "\n" +
                           "Email: " + emailCli + "\n");
                 */
                new ExibirCliente(nomeCli, sobrenomeCli, cpfCli, dataNascCli, sexoCli, generoCli, nomeSocialCli, telFixoCli, celularCli, emailCli).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Cliente Não Encontrado! ");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarCliActionPerformed

    private void txtNomeBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nomeCli;
        nomeCli = txtNomeBuscar.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM clientes WHERE nome LIKE ?");
            st.setString(1, "%" + nomeCli + "%");

            ResultSet clientes = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblClientes.getModel();
            tblModelo.setRowCount(0);

            while (clientes.next()) {
                String linha[] = {
                    clientes.getString("Nome"),
                    clientes.getString("Sobrenome"),
                    clientes.getString("CPF"),
                    clientes.getString("Data_nasc"),
                    clientes.getString("Tel_fix"),
                    clientes.getString("Tel_cel"),
                    clientes.getString("Email")
                };
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCliActionPerformed
        String cpfCliente;
        cpfCliente = JOptionPane.showInputDialog("Informe o CPF do Cliente a Ser Excluído:  ");
        if (cpfCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "[ERRO] Nenhum CPF Informado!");
        } else 
            try {
            int retorno = new SistemaGestaoDao().excluirCliente(cpfCliente);
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Cliente Excluído Com Sucesso!");
                listarClientes();
            } else {
                JOptionPane.showMessageDialog(null, "[ERRO] Cliente Nâo Encontrado!");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirCliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fecharListarClientes();
        mostrarMenuGestaoCli();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        String cpfCli;
        cpfCli = fmtCPFBuscar.getText();

        if (cpfCli.isBlank()) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: ");
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("select clientes.nome as nome, produtos.nomeProd as produto, DATE_FORMAT(pedido.data_compra, \"%d-%m-%Y\") as data, pedido.quant_compra as quantidade\n"
                    + "from pedido \n"
                    + "inner join clientes on clientes.cpf = pedido.fk_cpf\n"
                    + "inner join produtos on produtos.cod_prod = pedido.fk_cod_prod\n"
                    + "where pedido.fk_cpf = ?");
            st.setString(1, cpfCli);

            ResultSet compras = st.executeQuery();
            DefaultTableModel tblModelo2 = (DefaultTableModel) tblCompras.getModel();
            tblModelo2.setRowCount(0);

            while (compras.next()) {
                String linha[] = {
                    compras.getString("nome"),
                    compras.getString("produto"),
                    compras.getString("data"),
                    compras.getString("quantidade"),};
                tblModelo2.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnLimparCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCampoActionPerformed
        fmtCPFBuscar.setText("");
        listarClientes();
    }//GEN-LAST:event_btnLimparCampoActionPerformed

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        new CadastrarProduto().setVisible(true);
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdutoActionPerformed
        new ListarProdutos().setVisible(true);
    }//GEN-LAST:event_btnListarProdutoActionPerformed

    private void btnAltProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltProdutoActionPerformed
        new AlterarProduto().setVisible(true);
    }//GEN-LAST:event_btnAltProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        new ExcluirProduto().setVisible(true);
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void fmtCPFBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmtCPFBuscarMouseClicked

    }//GEN-LAST:event_fmtCPFBuscarMouseClicked

    private void btnNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCompraActionPerformed
        if (painelNovaCompra.isEnabled() && painelPedido.isEnabled()) {
            fecharNovaCompra();
            fecharPedido();
        } else {
            mostrarNovaCompra();
            mostrarPedido();
        }
    }//GEN-LAST:event_btnNovaCompraActionPerformed

    private void btnConfigUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigUsuarioActionPerformed
        
        
        new ConfiguracoesUsuarios().setVisible(true);
       
    }//GEN-LAST:event_btnConfigUsuarioActionPerformed

    private void fmtCPFBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmtCPFBuscarActionPerformed

    }//GEN-LAST:event_fmtCPFBuscarActionPerformed

    private void fmtCPFCliNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmtCPFCliNovaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmtCPFCliNovaCompraActionPerformed

    private void btnConfirmarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarProdutoActionPerformed
        if (tblNovaCompraProd.getSelectedRow() >= 0) {

            txtCodProdPedido.setText(tblNovaCompraProd.getValueAt(tblNovaCompraProd.getSelectedRow(), 0).toString());
            txtNomeProdNovaCompra.setText(tblNovaCompraProd.getValueAt(tblNovaCompraProd.getSelectedRow(), 1).toString());
            txtNomeProdPedido.setText(tblNovaCompraProd.getValueAt(tblNovaCompraProd.getSelectedRow(), 1).toString());

        } else {
            JOptionPane.showMessageDialog(null, "Clique No Produto Na Tabela! ");
        }
    }//GEN-LAST:event_btnConfirmarProdutoActionPerformed

    private void btnBuscarProdNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdNovaCompraActionPerformed
        String nomeProd;
        nomeProd = txtNomeProdNovaCompra.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM produtos WHERE nomeProd LIKE ?");
            st.setString(1, "%" + nomeProd + "%");

            ResultSet produto = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblNovaCompraProd.getModel();
            tblModelo.setRowCount(0);

            while (produto.next()) {
                String linha[] = {
                    produto.getString("cod_prod"),
                    produto.getString("nomeProd"),
                    produto.getString("qtd"),};
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarProdNovaCompraActionPerformed

    private void tblNovaCompraCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNovaCompraCliMouseClicked

    }//GEN-LAST:event_tblNovaCompraCliMouseClicked

    private void tblNovaCompraProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNovaCompraProdMouseClicked
        if (tblNovaCompraProd.getSelectedRow() >= 0) {

            txtNomeProdNovaCompra.setText(tblNovaCompraProd.getValueAt(tblNovaCompraProd.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_tblNovaCompraProdMouseClicked

    private void btnConfirmarCliNovaCOmpraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCliNovaCOmpraActionPerformed
        if (tblNovaCompraCli.getSelectedRow() >= 0) {
            txtCPFCliPedidoNovaCompra.setText(tblNovaCompraCli.getValueAt(tblNovaCompraCli.getSelectedRow(), 0).toString());
            txtNomeCliPedido.setText(tblNovaCompraCli.getValueAt(tblNovaCompraCli.getSelectedRow(), 1).toString());

        } else {
            JOptionPane.showMessageDialog(null, "Clique No Cliente Na Tabela! ");
        }
    }//GEN-LAST:event_btnConfirmarCliNovaCOmpraActionPerformed

    private void btnBuscarCli1NovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCli1NovaCompraActionPerformed
        String cpfCli;
        cpfCli = fmtCPFCliNovaCompra.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://bdremotosenac.mysql.database.azure.com:3306/remotosenac", "rootwellington", "Well1997##");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM clientes WHERE cpf LIKE ?");
            st.setString(1, "%" + cpfCli + "%");

            ResultSet cliente = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tblNovaCompraCli.getModel();
            tblModelo.setRowCount(0);

            while (cliente.next()) {
                String linha[] = {
                    cliente.getString("cpf"),
                    cliente.getString("nome"),
                    cliente.getString("sobrenome"),};
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarCli1NovaCompraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (painelNovaCompra.isEnabled() && painelPedido.isEnabled()) {
            fecharNovaCompra();
            fecharPedido();
        } else {
            mostrarNovaCompra();
            fecharPedido();
        }

        fmtCPFCliNovaCompra.setText("");
        txtNomeProdNovaCompra.setText("");
        txtCPFCliPedidoNovaCompra.setText("");
        txtNomeCliPedido.setText("");
        txtCodProdPedido.setText(""); 
        txtNomeProdPedido.setText("");
        txtQtdProdutoPedido.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarCompraActionPerformed
        String cpfCli = fmtCPFCliNovaCompra.getText();
        String nomeProd = txtNomeProdNovaCompra.getText();
        String nomeCli = txtNomeCliPedido.getText();

        if (cpfCli.isEmpty() || nomeProd.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos Vazios! Selecione Um Cliente e Um Produto! ");
        } else {

            try {
                int quantidade = Integer.parseInt(txtQtdProdutoPedido.getText());
                int codProd = Integer.parseInt(txtCodProdPedido.getText());

                new SistemaGestaoDao().novoPedido(cpfCli, nomeCli, codProd, nomeProd, quantidade);
                JOptionPane.showMessageDialog(null, "Compra Realizada com Sucesso");

                fmtCPFCliNovaCompra.setText("");
                txtNomeProdNovaCompra.setText("");

                txtCPFCliPedidoNovaCompra.setText("");
                txtNomeCliPedido.setText("");
                txtCodProdPedido.setText("");
                txtNomeProdPedido.setText("");
                txtQtdProdutoPedido.setText("");

            } catch (ClassNotFoundException | SQLException ex) {

                JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "[ERRO] Quantidade Vazia! Insira '' 0 '' se não houver unidades do Produto!");

            }

        }
    }//GEN-LAST:event_btnRealizarCompraActionPerformed

    private void txtCodProdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProdPedidoActionPerformed

    private void txtQtdProdutoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdProdutoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdProdutoPedidoActionPerformed

    private void txtNomeProdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAltProduto;
    private javax.swing.JButton btnAlterarCli;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.JButton btnBuscarCli1NovaCompra;
    private javax.swing.JButton btnBuscarProdNovaCompra;
    private javax.swing.JButton btnCadastrarCliente1;
    private javax.swing.JButton btnCadrastarCli;
    private javax.swing.JButton btnCancelarCadastro;
    private javax.swing.JButton btnConfigUsuario;
    private javax.swing.JButton btnConfirmarCliNovaCOmpra;
    private javax.swing.JButton btnConfirmarProduto;
    private javax.swing.JButton btnExcluirCli;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnGestaoClientes;
    private javax.swing.JButton btnHistoricoCompras;
    private javax.swing.JButton btnLimparCampo;
    private javax.swing.JButton btnListarCli;
    private javax.swing.JButton btnListarProduto;
    private javax.swing.JButton btnNovaCompra;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRealizarCompra;
    private javax.swing.JComboBox<String> cmbIdentidadeDeGenero;
    private javax.swing.JComboBox<String> cmbSexoBiologico;
    private javax.swing.JFormattedTextField fmtCPF;
    private javax.swing.JFormattedTextField fmtCPFBuscar;
    private javax.swing.JFormattedTextField fmtCPFCliNovaCompra;
    private javax.swing.JFormattedTextField fmtData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFBuscar;
    private javax.swing.JLabel lblCPFCli;
    private javax.swing.JLabel lblCPFCli1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblDadosPessoais;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblHistoricoDeCompras;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JLabel lblNomeCliBuscar;
    private javax.swing.JLabel lblNomeSocial;
    private javax.swing.JLabel lblNovaCompra;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSobrenomeCli;
    private javax.swing.JLabel lblTelFixo;
    private javax.swing.JLabel lblTituloCadastro;
    private javax.swing.JLabel lblgestaoClientes;
    private javax.swing.JPanel painelCadastrarCliente;
    private javax.swing.JPanel painelHistorico;
    private javax.swing.JPanel painelListarClientes;
    private javax.swing.JPanel painelMenuGestaoCli;
    private javax.swing.JPanel painelMenuLateral;
    private javax.swing.JPanel painelNovaCompra;
    private javax.swing.JPanel painelPedido;
    private javax.swing.JPanel painelProdutos;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTable tblNovaCompraCli;
    private javax.swing.JTable tblNovaCompraProd;
    private javax.swing.JTextField txtCPFCliPedidoNovaCompra;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCodProdPedido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFixo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeBuscar;
    private javax.swing.JTextField txtNomeCliPedido;
    private javax.swing.JTextField txtNomeProdNovaCompra;
    private javax.swing.JTextField txtNomeProdPedido;
    private javax.swing.JTextField txtNomeSocial;
    private javax.swing.JTextField txtQtdProdutoPedido;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
