/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import dao.SistemaGestaoDao;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author welli
 */
public class NovoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NovoUsuario
     */
    public NovoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastroUsu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        btnNovoUsuario = new javax.swing.JButton();
        ckMostrarSenhaUsu = new javax.swing.JCheckBox();
        pswUsu = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        painelCadastroUsu.setBackground(new java.awt.Color(204, 204, 204));

        painelCadastroUsu.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CADASTRAR USUARIO");
        painelCadastroUsu.add(jLabel2);
        jLabel2.setBounds(110, 10, 200, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SENHA:");
        painelCadastroUsu.add(jLabel3);
        jLabel3.setBounds(80, 130, 70, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("USUARIO:");
        painelCadastroUsu.add(jLabel4);
        jLabel4.setBounds(60, 70, 100, 40);
        painelCadastroUsu.add(txtUsu);
        txtUsu.setBounds(160, 70, 220, 40);

        btnNovoUsuario.setBackground(new java.awt.Color(51, 204, 0));
        btnNovoUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNovoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btnNovoUsuario.setText("CADASTRAR");
        btnNovoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });
        painelCadastroUsu.add(btnNovoUsuario);
        btnNovoUsuario.setBounds(110, 220, 170, 50);

        ckMostrarSenhaUsu.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        ckMostrarSenhaUsu.setForeground(new java.awt.Color(0, 0, 0));
        ckMostrarSenhaUsu.setText("Mostrar a senha");
        ckMostrarSenhaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMostrarSenhaUsuActionPerformed(evt);
            }
        });
        painelCadastroUsu.add(ckMostrarSenhaUsu);
        ckMostrarSenhaUsu.setBounds(160, 170, 170, 28);
        painelCadastroUsu.add(pswUsu);
        pswUsu.setBounds(160, 130, 220, 40);

        getContentPane().add(painelCadastroUsu);
        painelCadastroUsu.setBounds(40, 20, 420, 340);

        setSize(new java.awt.Dimension(511, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        String usu, senha;
        usu = txtUsu.getText();
        senha = pswUsu.getText();

        try {
            new SistemaGestaoDao().cadastrarUsuario(usu, senha);

            JOptionPane.showMessageDialog(null, "Usuario  Cadastrado com Sucesso");

            txtUsu.setText("");
            pswUsu.setText("");

        }catch (ClassNotFoundException | SQLException ex){
            if(ex.getMessage().contains("Duplicate entry")){
                JOptionPane.showMessageDialog(null, "Usuario já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void ckMostrarSenhaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMostrarSenhaUsuActionPerformed

        if(ckMostrarSenhaUsu.isSelected()){
            pswUsu.setEchoChar((char)0);
        }else {
            pswUsu.setEchoChar('*');
        }
    }//GEN-LAST:event_ckMostrarSenhaUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JCheckBox ckMostrarSenhaUsu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel painelCadastroUsu;
    private javax.swing.JPasswordField pswUsu;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
